apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: microservices
data:
  REDIS_URL: "redis://redis:6379"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  HOST: "0.0.0.0"
  PORT: "8000"
  CORS_ORIGINS: "http://localhost:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:6000"

