apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: microservices
data:
  DATABASE_PATH: "./data/products.db"
  JWT_ALGORITHM: "HS256"
  PORT: "4000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  CORS_ORIGINS: "http://localhost:3001"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  FAKESTORE_API_URL: "https://fakestoreapi.com"

